server:
  port: 8080
spring:
  application:
    name: seckillsystem
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    virtual-host: /
    port: 5672
    username: guest
    password: guest
    template:
      retry:
        enabled: true
        initial-interval: 3000
        max-attempts: 3
    listener:
      simple:
        concurrency: 50
        max-concurrency: 50
        prefetch: 1
        acknowledge-mode: auto

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/seckill_system?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 990515
mybatis-plus:
  type-aliases-package: com.jayce.seckillsystem.dao
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
